#include <bits/stdc++.h>
using namespace std;
#define ll long long 
#define vi vector<int>
#define pii pair<int,int>
const int INF = (int)1e9+7;

int n;
vi Scores, maxGames;
ll prefixSum[100][100];

ll 
int main()
{
    cin>>n;
    Scores.resize(n); maxGames.resize(n);
    for(int i=0;i<n;i++){
        cin>>Scores[i];
        cin>>maxGames[i];
    }
    memset(prefixSum,0,sizeof prefixSum);
    for(int i=0;i<n;i++){
        
        for(int j=;j<n;j++){

        }
    }

    return 0;
}